Enforce TLS Integration
canonical/sdcore-udr-operator pull request #20
Opened 2023-09-29 15:25 UTC by dariofaccin

# Description

Enforces TLS integration in the charm. Charm remains in blocked state until the `certificates` relation is created, and in waiting status until a certificate is stored.

# Checklist:

- [x] My code follows the [style guidelines](/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that validate the behaviour of the software
- [x] I validated that new and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have bumped the version of the library

2023-10-02 11:35 UTC, gruyaume requested changes

2023-10-02 11:35 UTC, gruyaume commented on tests/integration/test_integration.py
The tests are crashing here because we're lacking a relation

2023-10-03 11:33 UTC, patriciareinoso commented on tests/unit/test_charm.py
> +    def _create_certificates_relation(self) -> int:
is there really a need to create this method ?

2023-10-05 18:22 UTC, DanielArndt commented
@dariofaccin I didn't do anything here. I just re-ran it after the first build on my commit failed -- under the suspicion that maybe something cached on the runner. I'm not sure that makes any sense... but it succeeded this time...

2023-10-05 18:22 UTC, DanielArndt commented on tests/integration/test_integration.py
Fixed in https://github.com/canonical/sdcore-udr-operator/pull/20/commits/c3860c5ec514e6fcf1aaf152d087a97e88ebb609

2023-10-06 10:13 UTC, patriciareinoso approved these changes

2023-10-06 10:50 UTC, DanielArndt approved these changes

2023-10-06 11:15 UTC, gruyaume approved these changes

2023-10-06 12:34 UTC, merged